### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by asdwcx** [bxiang233/ForAINet#1]
when I tried to run eval.py based on the PointGroup-PAPER.pt you provided, a mistake happened:
(treeins) (base) root@d8fc5cfcc777:/home/ForAINet-main/PointCloudSegmentation#  python eval.py
/opt/conda/envs/treeins/lib/python3.8/site-packages/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
[2024-04-22 10:32:56,977][torch_points3d.trainer][INFO] - DEVICE : cuda
[2024-04-22 10:33:09,479][torch_points3d.metrics.model_checkpoint][INFO] - Loading checkpoint from /home/ForAINet-main/PointCloudSegmentation/checkpoint/PointGroup-PAPER.pt
Traceback (most recent call last):
  File "eval.py", line 13, in main
    trainer = Trainer(cfg)
  File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/trainer.py", line 48, in __init__
    self._initialize_trainer()
  File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/trainer.py", line 90, in _initialize_trainer
    self._dataset: BaseDataset = instantiate_dataset(self._checkpoint.data_config)
  File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/datasets/dataset_factory.py", line 46, in instantiate_dataset
    dataset = dataset_cls(dataset_config)
  File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/datasets/panoptic/treeins.py", line 629, in __init__
    self.test_dataset = dataset_cls(
  File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/datasets/segmentation/treeins.py", line 491, in __init__
    super().__init__(root, grid_size, *args, **kwargs)
  File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/datasets/segmentation/treeins.py", line 187, in __init__
    super(TreeinsOriginalFused, self).__init__(root, transform, pre_transform, pre_filter)
  File "/opt/conda/envs/treeins/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 60, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/opt/conda/envs/treeins/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 83, in __init__
    self._download()
  File "/opt/conda/envs/treeins/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 140, in _download
    self.download()
  File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/datasets/panoptic/treeins.py", line 562, in download
    super().download()
  File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/datasets/segmentation/treeins.py", line 517, in download
    super().download()
  File "/opt/conda/envs/treeins/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 50, in download
    raise NotImplementedError
NotImplementedError
 I downloaded the FOR-instance dataset and placed it in the correct location ,but I still get this issue, how did you fix it?

**Comment by bxiang233** [comment]
> when I tried to run eval.py based on the PointGroup-PAPER.pt you provided, a mistake happened: (treeins) (base) root@d8fc5cfcc777:/home/ForAINet-main/PointCloudSegmentation# python eval.py /opt/conda/envs/treeins/lib/python3.8/site-packages/MinkowskiEngine/**init**.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24. warnings.warn( [2024-04-22 10:32:56,977][torch_points3d.trainer][INFO] - DEVICE : cuda [2024-04-22 10:33:09,479][torch_points3d.metrics.model_checkpoint][INFO] - Loading checkpoint from /home/ForAINet-main/PointCloudSegmentation/checkpoint/PointGroup-PAPER.pt Traceback (most recent call last): File "eval.py", line 13, in main trainer = Trainer(cfg) File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/trainer.py", line 48, in **init** self._initialize_trainer() File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/trainer.py", line 90, in _initialize_trainer self._dataset: BaseDataset = instantiate_dataset(self._checkpoint.data_config) File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/datasets/dataset_factory.py", line 46, in instantiate_dataset dataset = dataset_cls(dataset_config) File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/datasets/panoptic/treeins.py", line 629, in **init** self.test_dataset = dataset_cls( File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/datasets/segmentation/treeins.py", line 491, in **init** super().**init**(root, grid_size, *args, **kwargs) File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/datasets/segmentation/treeins.py", line 187, in **init** super(TreeinsOriginalFused, self).**init**(root, transform, pre_transform, pre_filter) File "/opt/conda/envs/treeins/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 60, in **init** super().**init**(root, transform, pre_transform, pre_filter) File "/opt/conda/envs/treeins/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 83, in **init** self._download() File "/opt/conda/envs/treeins/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 140, in _download self.download() File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/datasets/panoptic/treeins.py", line 562, in download super().download() File "/home/ForAINet-main/PointCloudSegmentation/torch_points3d/datasets/segmentation/treeins.py", line 517, in download super().download() File "/opt/conda/envs/treeins/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 50, in download raise NotImplementedError NotImplementedError I downloaded the FOR-instance dataset and placed it in the correct location ,but I still get this issue, how did you fix it?

Hi, sorry for the late reply. Could you have a look at this issue? Hope it helps:
https://github.com/prs-eth/PanopticSegForLargeScalePointCloud/issues/10#issuecomment-2091561194

**Comment by WangLuo01** [comment]
I had the exact same problem with him and didn't find a solution

**Comment by bxiang233** [comment]
> I had the exact same problem with him and didn't find a solution

Hi, have you already tried this?
https://github.com/prs-eth/PanopticSegForLargeScalePointCloud/issues/10#issuecomment-2091561194

**Comment by WangLuo01** [comment]
![1721371163923](https://github.com/user-attachments/assets/c3eaa3b8-0e5b-4ce9-80bf-12b7b3cd3dc6)
你好，在更改路径后能运行了，但是会出现这样的情况，想知道我这样是对的嘛？如果等这个过程大概要等多久呢

**Comment by bxiang233** [comment]
> ![1721371163923](https://private-user-images.githubusercontent.com/67639365/350284442-c3eaa3b8-0e5b-4ce9-80bf-12b7b3cd3dc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzQ0MTksIm5iZiI6MTcyMTM3NDExOSwicGF0aCI6Ii82NzYzOTM2NS8zNTAyODQ0NDItYzNlYWEzYjgtMGU1Yi00Y2U5LTgwYmYtMTJiN2IzY2QzZGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA3MjgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZGVlNWI4NDIxODFlNDFkNjdlZGE0OWMzNmVlODJlOGNiOTJkMDA5YWQ3YTVjNjY3NTE0MGJkMTAzMzczOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._oYNLQdbU1SWakXQDN2_RmtnF8Z92bfBR7kMTyGuyhg) 你好，在更改路径后能运行了，但是会出现这样的情况，想知道我这样是对的嘛？如果等这个过程大概要等多久呢

看起来没问题，等进度条完成就好了。

**Comment by WangLuo01** [comment]
运行训练命令时我是可以正常训练的，但是python eval.py就会一直卡在百分之零

**Comment by bxiang233** [comment]
> 运行训练命令时我是可以正常训练的，但是python eval.py就会一直卡在百分之零

啊？没见过这个问题诶……你有更多的线索吗？不然我想不到有什么解决方法

**Comment by WangLuo01** [comment]
我现在也不是很清楚，正在进行训练，等结束了我再看一看

**Comment by WangLuo01** [comment]
想知道python eval.py大概会运行多久？

**Comment by WangLuo01** [comment]
总结一下我遇到的问题和解决方法：（1）NotImplementedError：这个问题应该是因为数据集和预训练模型的路径没有放在PointCloudSegmentation目录下，我模仿作者的文件路径存放后解决了这个问题（2）训练在第31个epoch停止，python eval.py会卡住，我想这两个是一个原因导致，参考作者之前提供的环境文件，把pip下没有安装或者版本不同的更改以后解决了问题

**Comment by hunanghuan03** [comment]
> 总结一下我遇到的问题和解决方法：（1）NotImplementedError：这个问题应该是因为数据集和预训练模型的路径没有放在PointCloudSegmentation目录下，我模仿作者的文件路径存放后解决了这个问题（2）训练在第31个epoch停止，python eval.py会卡住，我想这两个是一个原因导致，参考作者之前提供的环境文件，把pip下没有安装或者版本不同的更改以后解决了问题

您好，请问（1）的NotImplementedError是应该具体改什么路径呢
